import { Box, Flex, Heading, HStack, Text, useBreakpointValue } from "@chakra-ui/react";
import colors from "../../public/constants/colors/colors";
import Image from "next/image";

const FeatureCard = ({ num, heading, text, imgsrc }) => {
  const isMobileLayout = useBreakpointValue({ base: true, sm: false });

  return (
    <HStack
      alignItems="stretch"
      spacing={0}
      flexDir={isMobileLayout ? "column" : "row"}
      w="100%"
    >
      {isMobileLayout ? (
        <>
          <Box
            bg="white"
            rounded="xl"
            position="relative"
            p={5}
            py={10}
            w="100%"
            borderRadius="24px"
            mt={5}
          >
            <Text
              fontSize={80}
              color={colors.featureCardNumColor}
              fontWeight={700}
              w="max-content"
              ml={20}
            >
              {num}
            </Text>
            <Heading
              position="absolute"
              top={110}
              left={10}
              color={colors.darkGray}
              fontSize="28px"
            >
              {heading}
            </Heading>
            <Text
              fontSize="22px"
              color={colors.lightGray}
              pl={5}
              mt={4}
            >
              {text}
            </Text>
          </Box>
          <Flex
            bg={colors.purpleDark}
            justifyContent="center"
            alignItems="center"
            p={2}
            borderRadius="24px"
            w="100%"
          >
            <Image
              src={imgsrc}
              alt="feature-image"
              w={350}
              height={300}
            />
          </Flex>
        </>
      ) : (
        <>
          {num === "2" ? (
            <>
              <Flex
                bg={colors.purpleDark}
                justifyContent="center"
                alignItems="center"
                p={2}
                borderRadius="24px"
                w="50%"
              >
                <Image
                  src={imgsrc}
                  alt="feature-image"
                  w={350}
                  height={300}
                />
              </Flex>
              <Box
                bg="white"
                rounded="xl"
                position="relative"
                p={5}
                py={10}
                w="50%"
                borderRadius="24px"
                mt={5}
              >
                <Text
                  fontSize={80}
                  color={colors.featureCardNumColor}
                  fontWeight={700}
                  w="max-content"
                  ml={20}
                >
                  {num}
                </Text>
                <Heading
                  position="absolute"
                  top={110}
                  left={10}
                  color={colors.darkGray}
                  fontSize="28px"
                >
                  {heading}
                </Heading>
                <Text
                  fontSize="22px"
                  color={colors.lightGray}
                  pl={5}
                  mt={4}
                >
                  {text}
                </Text>
              </Box>
            </>
          ) : (
            <>
              <Box
                bg="white"
                rounded="xl"
                position="relative"
                p={5}
                py={10}
                w="50%"
                borderRadius="24px"
                mt={5}
              >
                <Text
                  fontSize={80}
                  color={colors.featureCardNumColor}
                  fontWeight={700}
                  w="max-content"
                  ml={20}
                >
                  {num}
                </Text>
                <Heading
                  position="absolute"
                  top={110}
                  left={10}
                  color={colors.darkGray}
                  fontSize="28px"
                >
                  {heading}
                </Heading>
                <Text
                  fontSize="22px"
                  color={colors.lightGray}
                  pl={5}
                  mt={4}
                >
                  {text}
                </Text>
              </Box>
              <Flex
                bg={colors.purpleDark}
                justifyContent="center"
                alignItems="center"
                p={2}
                borderRadius="24px"
                w="50%"
              >
                <Image
                  src={imgsrc}
                  alt="feature-image"
                  w={350}
                  height={300}
                />
              </Flex>
            </>
          )}
        </>
      )}
    </HStack>
  );
};

export default FeatureCard;
